global:
  resolve_timeout: 5m

route:
  receiver: 'webhook-notifications'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
- name: 'webhook-notifications'
  webhook_configs:
  - url: 'https://webhook.site/5606ba46-85fe-438f-95b4-2fe8ba53dd0e'
    send_resolved: true