apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-custom-config
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  alertmanager.yaml: |
    {{- $sec := lookup "v1" "Secret" .Release.Namespace .Values.alertmanager.smtp.secretName }}
    {{- $userKey := .Values.alertmanager.smtp.userKey }}
    {{- $passKey := .Values.alertmanager.smtp.passwordKey }}

    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: {{ index $sec.data $userKey | b64dec | quote }}
      smtp_auth_username: {{ index $sec.data $userKey | b64dec | quote }}
      smtp_auth_password: {{ index $sec.data $passKey | b64dec | quote }}
      smtp_require_tls: true


    route:
      receiver: 'email-notifications'
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
    - name: 'email-notifications'
      email_configs:
      - to: '{{ .Values.alertmanager.recipient }}'
        send_resolved: true
        headers:
          Subject: '[ALERT] {{ "{{" }} .GroupLabels.alertname {{ "}}" }} - SMS Checker'