apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-custom-config
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: '{{ .Values.alertmanager.smtp.user }}'
      smtp_auth_username: '{{ .Values.alertmanager.smtp.user }}'
      smtp_auth_password: '{{ .Values.alertmanager.smtp.password }}'
      smtp_require_tls: true

    route:
      receiver: 'email-notifications'
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
    - name: 'email-notifications'
      email_configs:
      - to: '{{ .Values.alertmanager.recipient }}'
        send_resolved: true
        headers:
          Subject: '[ALERT] {{ "{{" }} .GroupLabels.alertname {{ "}}" }} - SMS Checker'