apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-smtp-secret
  labels:
    app: {{ .Values.app.labels.app }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  SMTP_USER: {{ .Values.alertmanager.smtp.user | quote }}
  SMTP_PASSWORD: {{ .Values.alertmanager.smtp.password | quote }}