{{- if not .Values.istio.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  labels:
    app: {{ .Values.app.labels.app }}
    component: {{ .Values.app.labels.component }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.labels.app }}
      component: {{ .Values.app.labels.component }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.labels.app }}
        component: {{ .Values.app.labels.component }}
    spec:
      containers:
      - name: app
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.app.service.port }}
        envFrom:
          - configMapRef:
              name: {{ .Values.configMap.name }}

{{- end }}     