apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    app: {{ .Values.app.labels.app }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  APP_PORT: "{{ .Values.app.service.port }}"
  MODEL_HOST: "http://{{ .Values.modelService.service.name }}:{{ .Values.modelService.service.port }}"