{{- if .Values.versions.v1.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.modelService.name }}-deployment-v1
  labels:
    app: {{ .Values.modelService.labels.app }}
    version: v1  
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.versions.v1.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.modelService.labels.app }}
      version: v1  
  template:
    metadata:
      labels:
        app: {{ .Values.modelService.labels.app }}
        version: v1  
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.modelService.service.port }}"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: model
        image: "{{ .Values.modelService.image.repository }}:{{ .Values.versions.v1.imageTag }}"
        imagePullPolicy: {{ .Values.modelService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.modelService.service.port }}
          name: http
        
        env:
        - name: MODEL_VERSION
          value: "v1"
        - name: SMTP_USER 
          valueFrom: 
            secretKeyRef: 
              name: {{ .Values.secret.name }} 
              key: {{ .Values.secret.smtpUserKey }} 
        - name: SMTP_PASS 
          valueFrom: 
            secretKeyRef: 
              name: {{ .Values.secret.name }} 
              key: {{ .Values.secret.smtpPassKey }}
        
        volumeMounts:
        - name: model-storage
          mountPath: /mnt/shared-volume
        
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      
      volumes:
      - name: model-storage
        hostPath:
          path: {{ .Values.modelService.volume.hostPath }}
          type: DirectoryOrCreate
{{- end }}