---
# General setup tasks for all VMs
- name: General system setup
  hosts: all
  become: yes
  tasks:
    - name: Loop over public key files
      ansible.builtin.find:
        paths: "./keys"
        patterns: "*.pub"
      register: pubkey_files

    - name: Register public SSH keys
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item.path) }}"
      loop: "{{ pubkey_files.files }}"
      when: pubkey_files.matched | default(0) > 0

    - name: Disable swap 
      ansible.builtin.shell: swapoff -a
      args:
        warn: false

    - name: Remove swap entry
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^\s*[^#].*\s+swap\s+.*$'
        state: absent

    - name: Register automated module load for future boot
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: '0644'

    - name: Load overlay module
      ansible.builtin.modprobe:
        name: overlay
        state: present

    - name: Load br_netfilter module
      ansible.builtin.modprobe:
        name: br_netfilter
        state: present

    - name: Enable kernel properties for IPv4
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
        owner: root
        group: root
        mode: '0644'

    - name: Apply sysctl settings
      ansible.builtin.command: sysctl --system
      changed_when: false


