---
# General setup tasks for all VMs
- name: General system setup
  hosts: all
  become: yes
  tasks:
    - name: Register public SSH keys
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - "{{ playbook_dir }}/../keys/*.pub"

    - name: Disable swap
      ansible.builtin.shell: swapoff -a
      changed_when: false

    - name: Remove swap entry
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '^\s*[^#].*\s+swap\s+.*$'
        state: absent

    - name: Register automated module load for future boot
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: "0644"

    - name: Load overlay module
      ansible.builtin.modprobe:
        name: overlay
        state: present

    - name: Load br_netfilter module
      ansible.builtin.modprobe:
        name: br_netfilter
        state: present

    - name: Enable kernel properties for IPv4
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
        owner: root
        group: root
        mode: "0644"

    - name: Apply sysctl settings
      ansible.builtin.command: sysctl --system
      changed_when: false

    - name: Configure /etc/hosts for cluster node name resolution
      copy:
        src: "{{ playbook_dir }}/hosts"
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"
