---
# Worker node setup tasks
- name: Setup worker nodes
  hosts: node-*
  become: yes
  gather_facts: false
  tasks:
    # Step 18: Generate Join Command
    - name: Check if node is already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Create command for joining cluster
      ansible.builtin.shell: kubeadm token create --print-join-command
      delegate_to: ctrl
      register: join_command
      when: not kubelet_conf.stat.exists

    # Step 19: Run Join Command
    - name: Run join command
      ansible.builtin.shell: "{{ join_command.stdout }}"
      when:
        - join_command is defined
        - join_command.stdout is defined
        - not kubelet_conf.stat.exists
      args:
        creates: /etc/kubernetes/kubelet.conf
